/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ITipping {
  export type TipStruct = {
    tipper: AddressLike;
    creator: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    message: string;
    timestamp: BigNumberish;
  };

  export type TipStructOutput = [
    tipper: string,
    creator: string,
    token: string,
    amount: bigint,
    message: string,
    timestamp: bigint
  ] & {
    tipper: string;
    creator: string;
    token: string;
    amount: bigint;
    message: string;
    timestamp: bigint;
  };
}

export interface TippingContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ETH_ADDRESS"
      | "MAX_MESSAGE_LENGTH"
      | "MAX_RECENT_TIPS"
      | "creatorTips"
      | "creatorTokenTips"
      | "emergencyWithdraw"
      | "fund"
      | "getContractBalance"
      | "getContractTokenBalance"
      | "getCreatorTotalTips"
      | "getRecentTips"
      | "getTipCount"
      | "getTipsReceived"
      | "getTipsSent"
      | "owner"
      | "renounceOwnership"
      | "tip"
      | "tipsReceived"
      | "tipsSent"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractFunded"
      | "EmergencyWithdrawal"
      | "OwnershipTransferred"
      | "TipSent"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ETH_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MESSAGE_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_RECENT_TIPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creatorTips",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorTokenTips",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractTokenBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorTotalTips",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentTips",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTipCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTipsReceived",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTipsSent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tip",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tipsReceived",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tipsSent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ETH_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MESSAGE_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_RECENT_TIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorTips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorTokenTips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorTotalTips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentTips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTipCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTipsReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTipsSent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tipsReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tipsSent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ContractFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawalEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TipSentEvent {
  export type InputTuple = [
    tipper: AddressLike,
    creator: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    message: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tipper: string,
    creator: string,
    token: string,
    amount: bigint,
    message: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tipper: string;
    creator: string;
    token: string;
    amount: bigint;
    message: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    creator: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    token: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    token: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TippingContract extends BaseContract {
  connect(runner?: ContractRunner | null): TippingContract;
  waitForDeployment(): Promise<this>;

  interface: TippingContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ETH_ADDRESS: TypedContractMethod<[], [string], "view">;

  MAX_MESSAGE_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MAX_RECENT_TIPS: TypedContractMethod<[], [bigint], "view">;

  creatorTips: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        tipper: string;
        creator: string;
        token: string;
        amount: bigint;
        message: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  creatorTokenTips: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  fund: TypedContractMethod<[], [void], "payable">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getContractTokenBalance: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  getCreatorTotalTips: TypedContractMethod<
    [creator: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getRecentTips: TypedContractMethod<
    [creator: AddressLike, limit: BigNumberish],
    [ITipping.TipStructOutput[]],
    "view"
  >;

  getTipCount: TypedContractMethod<[creator: AddressLike], [bigint], "view">;

  getTipsReceived: TypedContractMethod<
    [creator: AddressLike],
    [bigint],
    "view"
  >;

  getTipsSent: TypedContractMethod<[tipper: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  tip: TypedContractMethod<
    [
      creator: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      message: string
    ],
    [void],
    "payable"
  >;

  tipsReceived: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  tipsSent: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ETH_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_MESSAGE_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_RECENT_TIPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creatorTips"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        tipper: string;
        creator: string;
        token: string;
        amount: bigint;
        message: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "creatorTokenTips"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractTokenBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCreatorTotalTips"
  ): TypedContractMethod<
    [creator: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentTips"
  ): TypedContractMethod<
    [creator: AddressLike, limit: BigNumberish],
    [ITipping.TipStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTipCount"
  ): TypedContractMethod<[creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTipsReceived"
  ): TypedContractMethod<[creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTipsSent"
  ): TypedContractMethod<[tipper: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tip"
  ): TypedContractMethod<
    [
      creator: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      message: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "tipsReceived"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tipsSent"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContractFunded"
  ): TypedContractEvent<
    ContractFundedEvent.InputTuple,
    ContractFundedEvent.OutputTuple,
    ContractFundedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawal"
  ): TypedContractEvent<
    EmergencyWithdrawalEvent.InputTuple,
    EmergencyWithdrawalEvent.OutputTuple,
    EmergencyWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TipSent"
  ): TypedContractEvent<
    TipSentEvent.InputTuple,
    TipSentEvent.OutputTuple,
    TipSentEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "ContractFunded(address,uint256)": TypedContractEvent<
      ContractFundedEvent.InputTuple,
      ContractFundedEvent.OutputTuple,
      ContractFundedEvent.OutputObject
    >;
    ContractFunded: TypedContractEvent<
      ContractFundedEvent.InputTuple,
      ContractFundedEvent.OutputTuple,
      ContractFundedEvent.OutputObject
    >;

    "EmergencyWithdrawal(address,uint256)": TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;
    EmergencyWithdrawal: TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TipSent(address,address,address,uint256,string,uint256)": TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;
    TipSent: TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;

    "Withdrawal(address,address,uint256,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
