/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ITipping {
  export type TipStruct = {
    tipper: AddressLike;
    creator: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    message: string;
    timestamp: BigNumberish;
  };

  export type TipStructOutput = [
    tipper: string,
    creator: string,
    token: string,
    amount: bigint,
    message: string,
    timestamp: bigint
  ] & {
    tipper: string;
    creator: string;
    token: string;
    amount: bigint;
    message: string;
    timestamp: bigint;
  };
}

export interface ITippingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCreatorTotalTips"
      | "getRecentTips"
      | "getTipsReceived"
      | "getTipsSent"
      | "tip"
      | "withdraw"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TipSent" | "Withdrawal"): EventFragment;

  encodeFunctionData(
    functionFragment: "getCreatorTotalTips",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentTips",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTipsReceived",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTipsSent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tip",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCreatorTotalTips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentTips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTipsReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTipsSent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace TipSentEvent {
  export type InputTuple = [
    tipper: AddressLike,
    creator: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    message: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tipper: string,
    creator: string,
    token: string,
    amount: bigint,
    message: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tipper: string;
    creator: string;
    token: string;
    amount: bigint;
    message: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    creator: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    token: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    token: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ITipping extends BaseContract {
  connect(runner?: ContractRunner | null): ITipping;
  waitForDeployment(): Promise<this>;

  interface: ITippingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCreatorTotalTips: TypedContractMethod<
    [creator: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getRecentTips: TypedContractMethod<
    [creator: AddressLike, limit: BigNumberish],
    [ITipping.TipStructOutput[]],
    "view"
  >;

  getTipsReceived: TypedContractMethod<
    [creator: AddressLike],
    [bigint],
    "view"
  >;

  getTipsSent: TypedContractMethod<[tipper: AddressLike], [bigint], "view">;

  tip: TypedContractMethod<
    [
      creator: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      message: string
    ],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCreatorTotalTips"
  ): TypedContractMethod<
    [creator: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentTips"
  ): TypedContractMethod<
    [creator: AddressLike, limit: BigNumberish],
    [ITipping.TipStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTipsReceived"
  ): TypedContractMethod<[creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTipsSent"
  ): TypedContractMethod<[tipper: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tip"
  ): TypedContractMethod<
    [
      creator: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      message: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TipSent"
  ): TypedContractEvent<
    TipSentEvent.InputTuple,
    TipSentEvent.OutputTuple,
    TipSentEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "TipSent(address,address,address,uint256,string,uint256)": TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;
    TipSent: TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;

    "Withdrawal(address,address,uint256,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
